### ISSUE TITLE
Is there a need for this_week?

### ISSUE THREAD

**Issue by Blendify** [ThisWeekInBlenderDev/source#8]
We have this setup but I do not think it is needed and say we remove it.

**Comment by Blendify** [comment]
Why is this closed? Should we keep it then?

**Comment by ideasman42** [comment]
URL's are just the date now: eg: https://thisweekinblenderdev.github.io/2017-11-25.html - so thought it was OK to close.

**Comment by Blendify** [comment]
I was talking about https://github.com/ThisWeekInBlenderDev/source/tree/master/content/this_week

**Comment by ideasman42** [comment]
I see.

Isn't it good to keep this for adding new content? - It's not included in the RSS feed.
